#!/usr/bin/env bash
# auto_pull.sh — pull all repos and trigger incremental re-index via graph_build
# Generated by vps_setup.sh — edit REPOS_DIR / MCP_URL / MCP_AUTH_TOKEN as needed.

set -euo pipefail

REPOS_DIR="${REPOS_DIR:-/opt/Personal-Code-Obsidian/repos}"
MCP_URL="${MCP_URL:-http://localhost:8002}"
MCP_AUTH_TOKEN="${MCP_AUTH_TOKEN:-}"
LOG="/opt/Personal-Code-Obsidian/auto_pull.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }

log "=== auto_pull started ==="

for repo_dir in "$REPOS_DIR"/*/; do
    [[ -d "$repo_dir/.git" ]] || continue
    repo=$(basename "$repo_dir")

    result=$(git -C "$repo_dir" pull --ff-only 2>&1 | tail -1)
    log "$repo: $result"

    # Trigger re-index only if there were changes
    if [[ "$result" != "Already up to date." ]]; then
        log "$repo: changes detected — triggering graph_build..."
        if [[ -n "$MCP_AUTH_TOKEN" ]]; then
            curl -s -X POST "$MCP_URL/sse" \
                -H "Authorization: Bearer $MCP_AUTH_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"method\":\"tools/call\",\"params\":{\"name\":\"graph_build\",\"arguments\":{\"repo_path\":\"$repo_dir\",\"force\":false}}}" \
                > /dev/null 2>&1 || log "$repo: graph_build request failed (server may be down)"
        fi
    fi
done

log "=== auto_pull done ==="
