#!/usr/bin/env bash
# =============================================================================
# vps_setup.sh — Clone all repos onto VPS and schedule auto-pull + re-index
#
# Usage:
#   chmod +x scripts/vps_setup.sh
#   GITHUB_TOKEN=ghp_xxxx ./scripts/vps_setup.sh
#
# What it does:
#   1. Creates ~/repos/ directory on the VPS
#   2. Clones all 8 repos (public + private via GITHUB_TOKEN)
#   3. Creates auto_pull.sh — pulls all repos and triggers re-index via webhook
#   4. Adds a cron job to run auto_pull.sh every 30 minutes
#
# Environment variables:
#   GITHUB_TOKEN    — GitHub personal access token (needs repo scope for private repos)
#   REPOS_DIR       — where to clone repos (default: ~/repos)
#   DB_PATH         — path to graph.db (default: ~/Personal-Code-Obsidian/data/graph.db)
#   MCP_URL         — base URL of the MCP server (default: http://localhost:8000)
#   MCP_AUTH_TOKEN       — Bearer token for the MCP server
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
GITHUB_USER="UshurbakiyevDavlat"
GITHUB_TOKEN="${GITHUB_TOKEN:-}"
REPOS_DIR="${REPOS_DIR:-/opt/Personal-Code-Obsidian/repos}"
DB_PATH="${DB_PATH:-/opt/Personal-Code-Obsidian/data/graph.db}"
MCP_URL="${MCP_URL:-http://localhost:8002}"
MCP_AUTH_TOKEN="${MCP_AUTH_TOKEN:-}"

# ── Repos list ────────────────────────────────────────────────────────────────
# Format: "repo_name:visibility"  (public | private)
REPOS=(
    "Personal-Code-Obsidian:public"
    "Personal-Knowledge-Agent:public"
    "PostgresMCP:public"
    "LinkedinMCP:public"
    "Telegram-Assistant-Agent:public"
    "mps:private"
    "operatorAgent:private"
    "ClaudeFork:private"
)

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
info() { log "✅ $*"; }
warn() { log "⚠️  $*"; }
err()  { log "❌ $*" >&2; }

check_token() {
    if [[ -z "$GITHUB_TOKEN" ]]; then
        warn "GITHUB_TOKEN not set — private repos will be skipped"
    fi
}

clone_url() {
    local repo="$1"
    local visibility="$2"
    if [[ "$visibility" == "private" && -n "$GITHUB_TOKEN" ]]; then
        echo "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${repo}.git"
    else
        echo "https://github.com/${GITHUB_USER}/${repo}.git"
    fi
}

# ── Step 1: Create repos directory ───────────────────────────────────────────
log "Creating repos directory: $REPOS_DIR"
mkdir -p "$REPOS_DIR"

# ── Step 2: Clone repos ───────────────────────────────────────────────────────
check_token

for entry in "${REPOS[@]}"; do
    repo="${entry%%:*}"
    visibility="${entry##*:}"
    target="$REPOS_DIR/$repo"

    if [[ "$visibility" == "private" && -z "$GITHUB_TOKEN" ]]; then
        warn "Skipping private repo '$repo' (no GITHUB_TOKEN)"
        continue
    fi

    url=$(clone_url "$repo" "$visibility")

    if [[ -d "$target/.git" ]]; then
        log "Already cloned: $repo — pulling latest..."
        git -C "$target" pull --ff-only 2>&1 | tail -1
    else
        log "Cloning $repo ($visibility)..."
        git clone "$url" "$target" --depth=1 2>&1 | tail -2
    fi
    info "Ready: $target"
done

# ── Step 3: Create auto_pull.sh ───────────────────────────────────────────────
AUTO_PULL="$HOME/auto_pull.sh"
log "Writing $AUTO_PULL"

cat > "$AUTO_PULL" << 'AUTOPULL'
#!/usr/bin/env bash
# auto_pull.sh — pull all repos and trigger incremental re-index via graph_build
# Generated by vps_setup.sh — edit REPOS_DIR / MCP_URL / MCP_AUTH_TOKEN as needed.

set -euo pipefail

REPOS_DIR="${REPOS_DIR:-/opt/Personal-Code-Obsidian/repos}"
MCP_URL="${MCP_URL:-http://localhost:8002}"
MCP_AUTH_TOKEN="${MCP_AUTH_TOKEN:-}"
LOG="$HOME/auto_pull.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }

log "=== auto_pull started ==="

for repo_dir in "$REPOS_DIR"/*/; do
    [[ -d "$repo_dir/.git" ]] || continue
    repo=$(basename "$repo_dir")

    result=$(git -C "$repo_dir" pull --ff-only 2>&1 | tail -1)
    log "$repo: $result"

    # Trigger re-index only if there were changes
    if [[ "$result" != "Already up to date." ]]; then
        log "$repo: changes detected — triggering graph_build..."
        if [[ -n "$MCP_AUTH_TOKEN" ]]; then
            curl -s -X POST "$MCP_URL/sse" \
                -H "Authorization: Bearer $MCP_AUTH_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"method\":\"tools/call\",\"params\":{\"name\":\"graph_build\",\"arguments\":{\"repo_path\":\"$repo_dir\",\"force\":false}}}" \
                > /dev/null 2>&1 || log "$repo: graph_build request failed (server may be down)"
        fi
    fi
done

log "=== auto_pull done ==="
AUTOPULL

chmod +x "$AUTO_PULL"
info "Created: $AUTO_PULL"

# ── Step 4: Add cron job ──────────────────────────────────────────────────────
CRON_JOB="*/30 * * * * REPOS_DIR=$REPOS_DIR MCP_URL=$MCP_URL MCP_AUTH_TOKEN=$MCP_AUTH_TOKEN $AUTO_PULL >> $HOME/auto_pull.log 2>&1"

log "Adding cron job (every 30 min)..."

# Add only if not already present
existing_cron=$(crontab -l 2>/dev/null || true)
if echo "$existing_cron" | grep -q "auto_pull.sh"; then
    warn "Cron job already exists — skipping"
else
    (echo "$existing_cron"; echo "$CRON_JOB") | crontab -
    info "Cron job added"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  VPS Setup Complete"
echo "============================================================"
echo ""
echo "  Repos cloned to : $REPOS_DIR"
echo "  Auto-pull script: $AUTO_PULL"
echo "  Cron interval   : every 30 min"
echo ""
echo "  Next steps:"
echo "  1. Set GITHUB_WEBHOOK_SECRET in .env and restart Docker"
echo "  2. Add webhook in each GitHub repo:"
echo "     URL:    https://davlat-obsidian.duckdns.org/webhook/github"
echo "     Type:   application/json"
echo "     Events: push"
echo "  3. Run initial graph_build for each repo via Cowork:"
echo "     graph_build(repo_path='$REPOS_DIR/<repo_name>')"
echo ""
